// Generated by Tools/calibrate_iso25d_sprites.swift — do not edit by hand.
// Regenerate after changing any Iso25D artwork:
//   swift Tools/calibrate_iso25d_sprites.swift \
//       UsedCarCity/Assets.xcassets UsedCarCity/Iso25DSpriteCalibration.swift
//
// Each entry locates the artwork's baked ground plate (the lot base diamond):
// the plate's measured pixel width fraction and its center point. The renderer
// scales each card so the plate spans exactly the projected grid footprint and
// anchors the plate center on the footprint center.

struct Iso25DSpriteCalibration: Hashable, Sendable {
    let footprintWidthFraction: Float
    let groundAnchorX: Float
    let groundAnchorY: Float

    static let byImageName: [String: Iso25DSpriteCalibration] = [
        "Iso25DCommercialGasStationB_East": .init(footprintWidthFraction: 0.8799, groundAnchorX: 0.5601, groundAnchorY: 0.5977),
        "Iso25DCommercialGasStationB_West": .init(footprintWidthFraction: 0.8945, groundAnchorX: 0.4473, groundAnchorY: 0.5972),
        "Iso25DConvenienceStore": .init(footprintWidthFraction: 0.9805, groundAnchorX: 0.5000, groundAnchorY: 0.5332),
        "Iso25DConvenienceStore_East": .init(footprintWidthFraction: 0.9199, groundAnchorX: 0.5400, groundAnchorY: 0.5703),
        "Iso25DConvenienceStore_North": .init(footprintWidthFraction: 0.7812, groundAnchorX: 0.4961, groundAnchorY: 0.7969),
        "Iso25DConvenienceStore_West": .init(footprintWidthFraction: 0.9814, groundAnchorX: 0.4995, groundAnchorY: 0.5371),
        "Iso25DDealerLarge_East": .init(footprintWidthFraction: 0.9814, groundAnchorX: 0.4985, groundAnchorY: 0.5669),
        "Iso25DDealerLarge_North": .init(footprintWidthFraction: 0.8271, groundAnchorX: 0.4399, groundAnchorY: 0.5928),
        "Iso25DDealerLarge_South": .init(footprintWidthFraction: 0.9355, groundAnchorX: 0.4766, groundAnchorY: 0.5957),
        "Iso25DDealerLarge_West": .init(footprintWidthFraction: 0.9365, groundAnchorX: 0.4761, groundAnchorY: 0.5869),
        "Iso25DDealerMedium_East": .init(footprintWidthFraction: 0.9805, groundAnchorX: 0.5068, groundAnchorY: 0.6006),
        "Iso25DDealerMedium_North": .init(footprintWidthFraction: 0.8594, groundAnchorX: 0.4541, groundAnchorY: 0.5991),
        "Iso25DDealerMedium_South": .init(footprintWidthFraction: 0.8594, groundAnchorX: 0.4541, groundAnchorY: 0.5991),
        "Iso25DDealerMedium_West": .init(footprintWidthFraction: 0.9609, groundAnchorX: 0.4941, groundAnchorY: 0.5991),
        "Iso25DDealerSmall": .init(footprintWidthFraction: 0.9609, groundAnchorX: 0.5000, groundAnchorY: 0.6265),
        "Iso25DDealer_East": .init(footprintWidthFraction: 0.9736, groundAnchorX: 0.4956, groundAnchorY: 0.6099),
        "Iso25DDealer_North": .init(footprintWidthFraction: 0.8604, groundAnchorX: 0.4458, groundAnchorY: 0.6011),
        "Iso25DDealer_West": .init(footprintWidthFraction: 0.9785, groundAnchorX: 0.5000, groundAnchorY: 0.6187),
        "Iso25DDowntownMixedUseA": .init(footprintWidthFraction: 0.8672, groundAnchorX: 0.5000, groundAnchorY: 0.6973),
        "Iso25DDowntownMixedUseA_East": .init(footprintWidthFraction: 0.8652, groundAnchorX: 0.5010, groundAnchorY: 0.7134),
        "Iso25DDowntownMixedUseA_North": .init(footprintWidthFraction: 0.8643, groundAnchorX: 0.5005, groundAnchorY: 0.7134),
        "Iso25DDowntownMixedUseA_West": .init(footprintWidthFraction: 0.8613, groundAnchorX: 0.4912, groundAnchorY: 0.7163),
        "Iso25DDowntownOfficeB_East": .init(footprintWidthFraction: 0.8682, groundAnchorX: 0.5024, groundAnchorY: 0.7012),
        "Iso25DDowntownOfficeB_West": .init(footprintWidthFraction: 0.8516, groundAnchorX: 0.4795, groundAnchorY: 0.7017),
        "Iso25DHighwayBigBoxB_East": .init(footprintWidthFraction: 0.9805, groundAnchorX: 0.5010, groundAnchorY: 0.5957),
        "Iso25DHighwayBigBoxB_West": .init(footprintWidthFraction: 0.9678, groundAnchorX: 0.4946, groundAnchorY: 0.5962),
        "Iso25DHighwayLogisticsA": .init(footprintWidthFraction: 0.9893, groundAnchorX: 0.4995, groundAnchorY: 0.5933),
        "Iso25DHighwayLogisticsA_East": .init(footprintWidthFraction: 0.9775, groundAnchorX: 0.4995, groundAnchorY: 0.6138),
        "Iso25DHighwayLogisticsA_North": .init(footprintWidthFraction: 0.9111, groundAnchorX: 0.5034, groundAnchorY: 0.5654),
        "Iso25DHighwayLogisticsA_West": .init(footprintWidthFraction: 0.9746, groundAnchorX: 0.4990, groundAnchorY: 0.6182),
        "Iso25DHouseGeneralA": .init(footprintWidthFraction: 0.9473, groundAnchorX: 0.5000, groundAnchorY: 0.6958),
        "Iso25DHouseGeneralA_East": .init(footprintWidthFraction: 0.9697, groundAnchorX: 0.5063, groundAnchorY: 0.6455),
        "Iso25DHouseGeneralA_North": .init(footprintWidthFraction: 0.8105, groundAnchorX: 0.4688, groundAnchorY: 0.5815),
        "Iso25DHouseGeneralA_West": .init(footprintWidthFraction: 0.9502, groundAnchorX: 0.5054, groundAnchorY: 0.6416),
        "Iso25DIndustrialFactoryA": .init(footprintWidthFraction: 0.9941, groundAnchorX: 0.5029, groundAnchorY: 0.5596),
        "Iso25DIndustrialFactoryA_East": .init(footprintWidthFraction: 0.9922, groundAnchorX: 0.5039, groundAnchorY: 0.5635),
        "Iso25DIndustrialFactoryA_North": .init(footprintWidthFraction: 0.8525, groundAnchorX: 0.4771, groundAnchorY: 0.5630),
        "Iso25DIndustrialFactoryA_West": .init(footprintWidthFraction: 0.9893, groundAnchorX: 0.4985, groundAnchorY: 0.5669),
        "Iso25DIndustrialLoadingWarehouseB_East": .init(footprintWidthFraction: 0.9570, groundAnchorX: 0.5000, groundAnchorY: 0.5596),
        "Iso25DIndustrialLoadingWarehouseB_West": .init(footprintWidthFraction: 0.9531, groundAnchorX: 0.5000, groundAnchorY: 0.5601),
        "Iso25DLuxuryPoolB_East": .init(footprintWidthFraction: 0.9658, groundAnchorX: 0.4956, groundAnchorY: 0.6143),
        "Iso25DLuxuryPoolB_West": .init(footprintWidthFraction: 0.9502, groundAnchorX: 0.4966, groundAnchorY: 0.6152),
        "Iso25DLuxuryVillaA": .init(footprintWidthFraction: 0.9766, groundAnchorX: 0.5010, groundAnchorY: 0.6255),
        "Iso25DLuxuryVillaA_East": .init(footprintWidthFraction: 0.9824, groundAnchorX: 0.5020, groundAnchorY: 0.6201),
        "Iso25DLuxuryVillaA_North": .init(footprintWidthFraction: 0.8916, groundAnchorX: 0.4507, groundAnchorY: 0.6113),
        "Iso25DLuxuryVillaA_West": .init(footprintWidthFraction: 0.9707, groundAnchorX: 0.4980, groundAnchorY: 0.6021),
        "Iso25DResidentialApartmentB_East": .init(footprintWidthFraction: 0.9688, groundAnchorX: 0.5049, groundAnchorY: 0.6479),
        "Iso25DResidentialApartmentB_West": .init(footprintWidthFraction: 0.9648, groundAnchorX: 0.4824, groundAnchorY: 0.6484),
        "Iso25DServiceWorkshop": .init(footprintWidthFraction: 0.9756, groundAnchorX: 0.5034, groundAnchorY: 0.5947),
        "Iso25DServiceWorkshop_East": .init(footprintWidthFraction: 0.9678, groundAnchorX: 0.5015, groundAnchorY: 0.5435),
        "Iso25DServiceWorkshop_North": .init(footprintWidthFraction: 0.9404, groundAnchorX: 0.4868, groundAnchorY: 0.5649),
        "Iso25DServiceWorkshop_West": .init(footprintWidthFraction: 0.8076, groundAnchorX: 0.5103, groundAnchorY: 0.5542),
    ]
}
